import React, { useEffect, useState } from 'react';
import { Box, Heart, LogOut, MapPin, Package, Settings, UserRound } from 'lucide-react';
import { ActiveTab, AuthUser, Order, Product } from '../types';
import { ApiService } from '../services/api';

interface AccountPageProps { user: AuthUser; token: string; setActiveTab: (tab: ActiveTab) => void; onLogout: () => void; }

export const AccountPage: React.FC<AccountPageProps> = ({ user, token, setActiveTab, onLogout }) => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [wishlist, setWishlist] = useState<Product[]>([]);
  useEffect(() => { ApiService.getOrders(token).then(result => setOrders(result.orders)); ApiService.getWishlist(token).then(result => setWishlist(result.products)); }, [token]);

  return <div className="bg-[#eaeded] min-h-[calc(100vh-160px)] py-8 px-4"><div className="max-w-6xl mx-auto space-y-5"><section className="bg-white p-6 border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-widest font-bold text-[#c4552d]">Your account</p><h1 className="text-3xl font-black text-[#172b3a] mt-1">Hello, {user.name}</h1><p className="text-sm text-slate-500 mt-1">Your orders, saved products, and shopping preferences.</p></div><button onClick={onLogout} className="flex items-center gap-2 text-sm font-bold text-[#007185] hover:underline"><LogOut className="w-4 h-4" /> Sign out</button></section><div className="grid md:grid-cols-3 gap-5">{[{ icon: <Package />, title: 'Your orders', text: `${orders.length} orders placed`, action: () => undefined }, { icon: <MapPin />, title: 'Addresses', text: 'Manage delivery addresses', action: () => undefined }, { icon: <Settings />, title: 'Login & security', text: 'Account protection is active', action: () => undefined }, { icon: <Heart />, title: 'Your lists', text: `${wishlist.length} saved products`, action: () => undefined }, { icon: <Box />, title: 'Track deliveries', text: 'See your latest order status', action: () => undefined }, { icon: <UserRound />, title: 'Shopping preferences', text: 'Open your AI recommendations', action: () => setActiveTab('recommend') }].map(item => <button key={item.title} onClick={item.action} className="bg-white border border-slate-200 p-5 text-left hover:shadow-md transition-shadow flex items-start gap-4"><span className="text-[#007185]">{item.icon}</span><span><strong className="block text-[#172b3a]">{item.title}</strong><span className="text-sm text-slate-500">{item.text}</span></span></button>)}</div><section className="bg-white border border-slate-200 p-5"><h2 className="text-xl font-bold text-[#172b3a]">Recent orders</h2>{orders.length === 0 ? <p className="text-sm text-slate-500 mt-4">Your orders will appear here after checkout.</p> : <div className="mt-4 space-y-3">{orders.slice(0, 5).map(order => <div key={order.id} className="border border-slate-200 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="text-xs text-slate-500">{order.id} · {new Date(order.createdAt).toLocaleDateString()}</p><p className="font-bold text-[#172b3a] mt-1">{order.items.length} item{order.items.length === 1 ? '' : 's'} · ₹{order.total.toLocaleString('en-IN')}</p></div><span className="text-xs font-bold px-3 py-1 bg-amber-50 text-amber-800 rounded-full">{order.status}</span></div>)}</div>}</section></div></div>;
};
